#!zsh

export dotfiles="$(dirname "$0")"

test -e $HOME/.zshrc.local && source $HOME/.zshrc.local
export KEYTIMEOUT=1

# Path to the oh-my-zsh installation.
export ZSH_CUSTOM=$dotfiles
export ZSH=$ZSH_CUSTOM/oh-my-zsh

if test ! -d "$ZSH"; then
	echo $ZSH does not exist!
	return 1
fi

ZSH_THEME="tuxie"

# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-syntax-highlighting git ruby screen zsh-autosuggestions vagrant fzf)

# User configuration

export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Some OSes don't understand screen.xterm-256color
test "$TERM" = "screen.xterm-256color" && export TERM=xterm-256color

if test -x $HOME/bin/edit; then
	export EDITOR=$HOME/bin/edit
else
	export EDITOR=vim
fi
alias e=$EDITOR
alias vi=vim
alias :q=exit

# export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export GOPATH=$HOME/.go
export GOBIN=$GOPATH/bin

export PATH=$HOME/bin:$PATH:$GOBIN

case $(uname -r) in
  *microsoft*) source $ZSH_CUSTOM/zshrc_windows
esac

case $(uname -s) in
  Darwin)  source $ZSH_CUSTOM/zshrc_macos ;;
  Linux)   source $ZSH_CUSTOM/zshrc_linux ;;
esac


source $ZSH/oh-my-zsh.sh

# I prefer ls' default colors
unset LSCOLORS

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=23'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if test "$LC_EXTRATERM_COOKIE" != ""; then
  export TERM_PROGRAM=Extraterm
fi

alias crystal='sudo docker run --user `id -u`:`id -g` --rm -it -v ${PWD}:/src -w /src jrei/crystal-alpine crystal'

