#!zsh

export HOMEBREW_GITHUB_API_TOKEN="cf48e0e887858c152d61b622703b94fa1ed493dc"

plugins+=osx
plugins+=textmate

alias ge="mate --no-recent" 
alias flushdns='sudo killall -HUP mDNSResponder;sudo killall mDNSResponderHelper;sudo dscacheutil -flushcache'
# alias mpv=/Applications/mpv.app/Contents/MacOS/mpv
alias burp="brew update && brew upgrade && brew cask upgrade && brew cleanup && echo Done."

case $(ifconfig en0 | awk '/ether/ {print $2}') in
	c8:2a:14:4d:48:cf)
		export HOST=imac
		;;
	8c:85:90:ca:89:12)
		export HOST=trustly
		alias tunnel='/usr/local/MacGPG2/bin/gpg2 --card-status >/dev/null ; ssh -N -f tunnel && echo Tunnel started || echo Tunnel failed'
		;;
esac

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

#% brew link ruby
#Warning: Refusing to link macOS-provided software: ruby
#If you need to have ruby first in your PATH run:
#  echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc
##export PATH="/usr/local/opt/ruby/bin:$PATH"
#For compilers to find ruby you may need to set:
##export LDFLAGS="-L/usr/local/opt/ruby/lib"
##export CPPFLAGS="-I/usr/local/opt/ruby/include"
#For pkg-config to find ruby you may need to set:
##export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"


export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
